
# SEO settings
title: ""
title2: "" # default: ""
description: "Jerome Dinal Herath"
keywords: "jerome, dinal, herath, Sri Lanka, Binghamton, colombo, univeristy, uoc, computer, science, blog, SUNY, data, scientist"
url: http://dinalherath.com # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

# google_analytics: G-JMGDT16E1T
google_analytics: UA-99988883-1
# repo:
# disqus_shortname: ""
# twitter_username: ""
# comments: true # or false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: expanded #compressed # expanded

# Author settings
author:
  name     : "Jerome Dinal Herath"
  job      : "Security Data Scientist @ Obsidian Security"
  greeting : ""
  bio      : ""
  thumb    : #/assets/images/sherlock.jpg
  email    : #hnrird@gmail.com
  url      : #http://heiswayi.github.io
  github   : #http://github.com/heiswayi
  twitter  : #http://twitter.com/HeiswayiNrird
  facebook : #https://www.facebook.com/heiswayi.nrird
  linkedin : #http://linkedin.com/in/nrird

# social settings
og_locale: "en_US"
#twitter_card: "summary_large_image"
#twitter_site: "@HeiswayiNrird"

plugins:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  #- slug : blog
  #  title: Blog
  - slug : contact
    title: Contact

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
